In [1]:
import numpy

In [3]:
arr = numpy.array([[4,3,2], [10,1,0],[5,8,24]])
arr

array([[ 4,  3,  2],
       [10,  1,  0],
       [ 5,  8, 24]])

In [4]:
numpy.amin(arr)

0

In [5]:
numpy.amin(arr, axis=0) # find minimum in each column

array([4, 1, 0])

In [6]:
numpy.amin(arr, axis=1) # .. in each row

array([2, 0, 5])

In [7]:
numpy.max(arr) == numpy.amax(arr) # axis max without axis gives max for all elements

True

Meadin, meanm StdDev can be used for all values or axises

In [8]:
numpy.mean(arr)

6.333333333333333

In [9]:
numpy.mean(arr, axis=1)

array([ 3.        ,  3.66666667, 12.33333333])

In [10]:
numpy.percentile(arr, 50) # under 50%

4.0

In [11]:
deg = numpy.array([0,30,45,60,90])
numpy.sin(deg*numpy.pi/180)

array([0.        , 0.5       , 0.70710678, 0.8660254 , 1.        ])

In [13]:
# Here is the equivalent code in pure Python without using NumPy

import math

deg = [0, 30, 45, 60, 90]
sin_values = [math.sin(math.radians(d)) for d in deg]
sin_values

[0.0, 0.49999999999999994, 0.7071067811865475, 0.8660254037844386, 1.0]

In [17]:
numpy.arcsin(sin_values)*180/numpy.pi

array([ 0., 30., 45., 60., 90.])

In [18]:
numpy.floor(sin_values)

array([0., 0., 0., 0., 1.])