In [2]:
import numpy as np

In [5]:
array_1d = np.array( [1,2,3,4,5,6])
array_2d = np.array( [[1,2,3], [4,5,6]])
array_3d = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10, 11, 12]]])

In [6]:
array_1d[0]

1

In [7]:
array_1d[-1]

6

In [11]:
array_2d[0,-1]

3

In [16]:
array_3d[-1,-1,-1]

12

In [17]:
array_1d[1:] # start from 1 and to the end

array([2, 3, 4, 5, 6])

In [19]:
array_1d[2:4]

array([3, 4])

In [22]:
array_1d[-3:-1]

array([4, 5])

In [24]:
array_2d[1,2:]

array([6])

In [26]:
array_3d[0,0,0:]

array([1, 2, 3])