In [7]:
import numpy as np;

A 0D array, also known as a scalar, is an array with no dimensions. It contains exactly one element.

The point of a 0D array in NumPy is to provide a uniform interface. All elements in NumPy, whether they are 0D (scalars), 1D (vectors), 2D (matrices), or higher-dimensional, are treated as arrays. This allows for consistent and efficient operations across different dimensional data.

For example, you can use the same methods and operations on a 0D array that you can use on higher dimensional arrays. This can simplify the code and make it easier to work with different dimensions of data.

In [11]:
x = np.array(24) # 0D array
y = np.array(16) 
x+y

40

In [14]:
oneD = np.array([1,2,3,4])
twoD = np.array([[1,1,1],[2,2,2],[3,3,3]])
threeD = np.array([[[1,1],[2,2],[3,3],[4,4], [1,1],[2,2],[3,3],[4,4]],
                  [[1,1],[2,2],[3,3],[4,4], [1,1],[2,2],[3,3],[4,4]]])

arrays = [oneD, twoD, threeD]

for arr in arrays:
    print(arr, end = "\n\n")

[1 2 3 4]

[[1 1 1]
 [2 2 2]
 [3 3 3]]

[[[1 1]
  [2 2]
  [3 3]
  [4 4]
  [1 1]
  [2 2]
  [3 3]
  [4 4]]

 [[1 1]
  [2 2]
  [3 3]
  [4 4]
  [1 1]
  [2 2]
  [3 3]
  [4 4]]]



In [15]:
threeD.shape

(2, 8, 2)

In [16]:
threeD.ndim

3

In [18]:
arr_1 = np.array([x for x in range(1,10)])
arr_1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
arr_2 = np.arange(1,10,1)
np.array_equal(arr_1, arr_2)

True

In [23]:
arr_1.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
arr_3 = np.array([x for x in range(0,12)])
arr_3.reshape(2,2,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [25]:
arr_3.reshape(3,2,2)

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

Dynamic calculation of 3rd dimension size, use -1

In [28]:
arr_3.reshape(2,2,-1)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [29]:
threeD = arr_3.reshape(2,2,-1)
threeD.reshape(-1) # flatten

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])