In [2]:
import numpy as np

In [4]:
A = np.array([[1,2,1],[2,4,2]])
B = np.array([5,5,5])
print(A)
print(B)

[[1 2 1]
 [2 4 2]]
[5 5 5]


In [5]:
np.add(A,B)

array([[6, 7, 6],
       [7, 9, 7]])

In [6]:
np.subtract(B,A)

array([[4, 3, 4],
       [3, 1, 3]])

In [10]:
A-B

array([[-4, -3, -4],
       [-3, -1, -3]])

In [11]:
np.divide(B,A)

array([[5.  , 2.5 , 5.  ],
       [2.5 , 1.25, 2.5 ]])

In [12]:
B/A

array([[5.  , 2.5 , 5.  ],
       [2.5 , 1.25, 2.5 ]])

In [13]:
np.power(A,2)

array([[ 1,  4,  1],
       [ 4, 16,  4]])

In [14]:
np.power(A,B)

array([[   1,   32,    1],
       [  32, 1024,   32]])