In [14]:
import numpy as np

In [15]:
first_np_array = np.array([1,2,3,4])
print(first_np_array)

[1 2 3 4]


In [16]:
zerros_np_array = np.zeros((3,3))
print(zerros_np_array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [17]:
ones_array = np.ones((4,4))
print(ones_array)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [21]:
empty_array = np.empty((2,2))
print(empty_array) 
empty_array.fill(1.5)
print(empty_array) 

[[1.5 1.5]
 [1.5 1.5]]
[[1.5 1.5]
 [1.5 1.5]]


In [27]:
from numpy import double
arrange_array = np.arange(-1, 1, 0.1, dtype=double)
print(arrange_array)

[-1.00000000e+00 -9.00000000e-01 -8.00000000e-01 -7.00000000e-01
 -6.00000000e-01 -5.00000000e-01 -4.00000000e-01 -3.00000000e-01
 -2.00000000e-01 -1.00000000e-01 -2.22044605e-16  1.00000000e-01
  2.00000000e-01  3.00000000e-01  4.00000000e-01  5.00000000e-01
  6.00000000e-01  7.00000000e-01  8.00000000e-01  9.00000000e-01]


In [29]:
# arrange_array = arrange_array.reshape(4,5)
# print(arrange_array)
arrange_array.reshape(4,5) # Juppiter automatically prints return values

array([[-1.00000000e+00, -9.00000000e-01, -8.00000000e-01,
        -7.00000000e-01, -6.00000000e-01],
       [-5.00000000e-01, -4.00000000e-01, -3.00000000e-01,
        -2.00000000e-01, -1.00000000e-01],
       [-2.22044605e-16,  1.00000000e-01,  2.00000000e-01,
         3.00000000e-01,  4.00000000e-01],
       [ 5.00000000e-01,  6.00000000e-01,  7.00000000e-01,
         8.00000000e-01,  9.00000000e-01]])

In [30]:
linspace = np.linspace(1,6,5)
linspace

array([1.  , 2.25, 3.5 , 4.75, 6.  ])

In [34]:
oneD = np.arange(-15, 15, 2)
oneD

array([-15, -13, -11,  -9,  -7,  -5,  -3,  -1,   1,   3,   5,   7,   9,
        11,  13])

In [36]:
#twoD = oneD.reshape(2,8) # ERROR: cannot reshape array of size 15 into shape (2,8)
twoD = oneD.reshape(3,5)
twoD

array([[-15, -13, -11,  -9,  -7],
       [ -5,  -3,  -1,   1,   3],
       [  5,   7,   9,  11,  13]])

In [38]:
threeD = np.arange(27).reshape(3,3,3)
threeD

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])